apiVersion: v1
kind: Service
metadata:
  labels:
    name: dns
  name: dns
spec:
  type: LoadBalancer
  ports:    
    - protocol: UDP      
      port: 53
      targetPort: 53
  selector:
    app: dnsserver  
  