apiVersion: v1
kind: Service
metadata:
  labels:
    name: adminui
  name: adminui
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP      
      port: 80
      targetPort: 8080    
  selector:
    app: dnsserver
  